 export const dataProfile = [

{
    login: "defunkt",
    id: 2,
    node_id: "MDQ6VXNlcjI=",
    avatar_url: "https://avatars.githubusercontent.com/u/2?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/defunkt",
    html_url: "https://github.com/defunkt",
    followers_url: "https://api.github.com/users/defunkt/followers",
    following_url: "https://api.github.com/users/defunkt/following{/other_user}",
    gists_url: "https://api.github.com/users/defunkt/gists{/gist_id}",
    starred_url: "https://api.github.com/users/defunkt/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/defunkt/subscriptions",
    organizations_url: "https://api.github.com/users/defunkt/orgs",
    repos_url: "https://api.github.com/users/defunkt/repos",
    events_url: "https://api.github.com/users/defunkt/events{/privacy}",
    received_events_url: "https://api.github.com/users/defunkt/received_events",
    type: "User",
    site_admin: false,
    name: "Chris Wanstrath",
    company: null,
    blog: "http://chriswanstrath.com/",
    location: null,
    email: null,
    hireable: null,
    bio: "🍔",
    twitter_username: null,
    public_repos: 107,
    public_gists: 273,
    followers: 21318,
    following: 210,
    created_at: "2007-10-20T05:24:19Z",
    updated_at: "2021-07-29T11:10:23Z"
  },

  {
    login: "mojombo",
    id: 1,
    node_id: "MDQ6VXNlcjE=",
    avatar_url: "https://avatars.githubusercontent.com/u/1?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mojombo",
    html_url: "https://github.com/mojombo",
    followers_url: "https://api.github.com/users/mojombo/followers",
    following_url: "https://api.github.com/users/mojombo/following{/other_user}",
    gists_url: "https://api.github.com/users/mojombo/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mojombo/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mojombo/subscriptions",
    organizations_url: "https://api.github.com/users/mojombo/orgs",
    repos_url: "https://api.github.com/users/mojombo/repos",
    events_url: "https://api.github.com/users/mojombo/events{/privacy}",
    received_events_url: "https://api.github.com/users/mojombo/received_events",
    type: "User",
    site_admin: false,
    name: "Tom Preston-Werner",
    company: "@chatterbugapp, @redwoodjs, @preston-werner-ventures ",
    blog: "http://tom.preston-werner.com",
    location: "San Francisco",
    email: null,
    hireable: null,
    bio: null,
    twitter_username: "mojombo",
    public_repos: 63,
    public_gists: 62,
    followers: 22765,
    following: 11,
    created_at: "2007-10-20T05:24:19Z",
    updated_at: "2021-11-19T02:02:00Z"
  }

  ,

  {
    login: "markosavicmidusa",
    id: 89229300,
    node_id: "MDQ6VXNlcjg5MjI5MzAw",
    avatar_url: "https://avatars.githubusercontent.com/u/89229300?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/markosavicmidusa",
    html_url: "https://github.com/markosavicmidusa",
    followers_url: "https://api.github.com/users/markosavicmidusa/followers",
    following_url: "https://api.github.com/users/markosavicmidusa/following{/other_user}",
    gists_url: "https://api.github.com/users/markosavicmidusa/gists{/gist_id}",
    starred_url: "https://api.github.com/users/markosavicmidusa/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/markosavicmidusa/subscriptions",
    organizations_url: "https://api.github.com/users/markosavicmidusa/orgs",
    repos_url: "https://api.github.com/users/markosavicmidusa/repos",
    events_url: "https://api.github.com/users/markosavicmidusa/events{/privacy}",
    received_events_url: "https://api.github.com/users/markosavicmidusa/received_events",
    type: "User",
    site_admin: false,
    name: "Marko Savic",
    company: null,
    blog: "",
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 1,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: "2021-08-19T23:56:19Z",
    updated_at: "2021-09-14T16:30:18Z"
  }

]